### ISSUE TITLE
external script execution

### ISSUE THREAD

**Issue by AltHaoX** [hobbyquaker/homekit2mqtt#48]
Hello,

I was wondering, is it possible to execute external python scrip in addition to MQTT functionality? Which piece of code to change to perform such action?

**Comment by hobbyquaker** [comment]
No, thats not possible (until now). I would also prefer to keep this whole thing "MQTT-only". But you could use e.g. https://github.com/hobbyquaker/mqttpc to control a script via a MQTT messages. If you want to work completely without MQTT I would suggest to use https://github.com/nfarina/homebridge instead of homekit2mqtt.

**Comment by AltHaoX** [comment]
Ok thanks
