### ISSUE TITLE
Adding more sensor types

### ISSUE THREAD

**Issue by matsekberg** [hobbyquaker/homekit2mqtt#54]
I would like to add sensors like energy, water usage etc. Can I have any pointers on how to accomplish that? Does HAP-NodeJS also needs to be changed?

**Comment by mattsheffiel** [comment]
I don't think that is possible at this time. Not because of anything on the homekit2mqtt or HAP-NodeJS end but because Apple hasn't added support for those types of sensors yet. I could definitely be wrong but I've not seen energy or water usage listed anywhere.

I believe the HAP protocol supports creating custom services and characteristics but you would have to write your own iOS app to see or manipulate anything custom. It wouldn't show up in the Home app for example.

They did add support for faucets (I'm not sure if this is available in HAP-NodeJS yet) but it was just turning them on/off and seeing if they are on/off at this point. I assumed you meant something more along the lines of gallons used or something like that. Hope that helps.

**Comment by matsekberg** [comment]
Thanks for your answer!
You are probably right, the custom services requires an app that can view the sensor data.
But a custom accessory could be added to hap-nodejs, homekit2mqtt would support it and emit MQTT messages right?

Btw I think I have seen a power outlet plug with energy readings but the manufacturer had a supporting app.

I wonder if there are any open source HomeKit apps out there?

**Comment by mattsheffiel** [comment]
> But a custom accessory could be added to hap-nodejs, homekit2mqtt would support it and emit MQTT messages right?

I'm pretty sure this is possible but haven't tried it. I'm also not sure what the policy is with HAP-NodeJS regarding custom characteristics being pulled into the master so you might have to make and use your own fork of the code to achieve this.

> I wonder if there are any open source HomeKit apps out there?

[This](https://github.com/KhaosT/HomeKit-Demo) might be a good place to start. It was created by KhaosT who also created HAP-NodeJS.

Are you trying to add HomeKit support to something you already have or are you making your own sensors for water and energy usage? I have to imagine that support for that type of sensing will inevitably be added to the protocol so don't let it not being there at the moment discourage you. You could always build the project out using MQTT and add HomeKit support down the road if/when support is added.

**Comment by matsekberg** [comment]
Yes I’m making an energy sensor and a water sensor. Thanx for the link.
