### ISSUE TITLE
json MQTT payload problem

### ISSUE THREAD

**Issue by AltHaoX** [hobbyquaker/homekit2mqtt#63]
Hello, I have encountered a problem with using json as a string MQTT payload. The broker doesnt recognise the payload and in "-v debug" it shows as undefined, yet it triggers events that arent supposted to happen. 

At first I thought it has to do with characters like { and " that json contains, but further inspection in config file it was all secured with \ so i really dont know what is happening here...

![screen shot 2018-01-28 at 18 39 46](https://user-images.githubusercontent.com/30388403/35485221-bc9c1786-045c-11e8-9990-2bd8c8efb3e8.png)

![screen shot 2018-01-28 at 18 49 22](https://user-images.githubusercontent.com/30388403/35485271-625b3846-045d-11e8-9835-c863f7c2521f.png)

![screen shot 2018-01-28 at 18 40 03](https://user-images.githubusercontent.com/30388403/35485220-bc7f0a88-045c-11e8-904b-ee378f52e9d1.png)

I hope this will be enough to identify the bug or my mistake, thanks you for your time!!

**Comment by hobbyquaker** [comment]
I think that's because homekit2mqtt tries to find a `val` property when it receives json payloads (that's the "[mqtt-smarthome](https://github.com/mqtt-smarthome) way"). I will think about how to handle that in a more unopinionated way, perhaps I have to introduce a new command line param like e.g. `--disable-mqtt-smarthome-payload-parsing` or smth. Or just hand through the string if val is undefined... give me a bit time, will try to have a solution by the next weekend.

**Comment by matsekberg** [comment]
What about a configuration item that is jsonpath?
http://goessner.net/articles/JsonPath/

**Comment by hobbyquaker** [comment]
smth like json path could be useful, yes. But @AltHaoX doesn't want to get a specific property, he wants to get the payload as plain string without any parsing at all (if I understand that right?)

**Comment by AltHaoX** [comment]
yes, I am planning to use the JSON just as a plain string - (at least on the side of homekit2mqtt), thanks!

**Comment by hobbyquaker** [comment]
Should work in v0.7.7 if you start with `--disable-json-parse`.

**Comment by AltHaoX** [comment]
just tested it, works flawlessly, many thanks!
