### ISSUE TITLE
Do we really want/need to cast the strings "true" and "false" to bool?

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homekit2mqtt#66]
```javascript
function typeGuess(payload) {
    let state;
    // Nasty type guessing.
    // TODO clarify Do we really want/need to cast the strings "true" and "false" to bool?
    if (payload === 'true') {
        state = true;
    } else if (payload === 'false') {
        state = false;
    } else if (isNaN(payload)) {
        state = payload;
    } else {
        state = parseFloat(payload);
    }
    return state;
}
```

**Comment by vanschroeder** [comment]
I would always recommend casting to the intended type as a means to evaluate values.
However, I see explicit value checking in your example rather than type casting.

Here's an example that type casts the value to evaluate

```
function typeGuess(payload) {
    let state;
    const boolVal = Boolean(payload);
    if (boolVal instanceof Boolean === true) {
        state = boolVal;
    } else if (isNaN(payload)) {
        state = payload;
    } else {
        state = parseFloat(payload);
    }
    return state;
}

console.log(`payload is 'true': ${typeGuess('true')}`);
console.log(`payload is 'false': ${typeGuess('false')}`);
console.log(`payload as a string: ${typeGuess('lala')}`);
console.log(`payload as a float: ${typeGuess('3.50')}`);
/*
	// caveat: actual bool would require special handling:
  console.log(`payload as a bool: ${typeGuess(false)}`);
	// could be handled by termary ooperator detecting if payload is bool when defining `boolVal`
*/
```

[see fiddle](https://jsfiddle.net/vanschroeder/xxspbfxu/)

The example makes no attempt test for actual booleans since it seems you are interpreting string values, so such a test is likely unnecessary

**Comment by hobbyquaker** [comment]
yeah, but the thing is: the type of the incoming payload is _always_ string.

**Comment by hobbyquaker** [comment]
see https://jsfiddle.net/5b3dfzu0/ - your typeGuess returns strings for `"true"` and `"false"`.

**Comment by hobbyquaker** [comment]
The question is: when someone publishes `true` or `false` on MQTT (what is received as a string) - do we want to convert that to Booleans because we think that this is what the publisher really means (and homekit2mqtt payload conf would be boolean) or do we just keep it as string and the user would have to configure string payload. 
For numbers I think it's quite clear, these should get parseFloat - but Booleans - I'm not so sure...

**Comment by vanschroeder** [comment]
I got ya -- this is an issue I encountered a couple years ago and thought I solved. Seems I forgot my own solution, which was to manually cast after evaluating the value. The problem is the `Boolean` Object kind of sucks since unlike Date and other JS Natives, it does not parse, so you can't typecast

So yes, value checking is the only solution here to cast a String to Boolean
You could use a regexp like so: `payload.match(/^(true|false)$/) !== null` then handle the value of the match to manually cast to `true|false` 

You can find more on this here:
https://stackoverflow.com/questions/263965/how-can-i-convert-a-string-to-boolean-in-javascript

Sucks, but thanks for bringing this up. This is one of those issues that do come up rather infrequently but show some of the failings of ecmascript

So yes, your code snippet is technically correct

**Comment by hobbyquaker** [comment]
After thinking over that for a while I came to the conclusion that I just keep the existing behavior (also for the sake of compatibility...)
