### ISSUE TITLE
Same topic for set and status?

### ISSUE THREAD

**Issue by sembsa** [hobbyquaker/homekit2mqtt#86]
Hi,

I write this same topic on setOn and statusOn and payload String on:off in onTrue/onFalse.
When i turn off LightBulb and close Home.app, reopen app state is On when the bulb is turned off. Before version is working. I mayber i put wrong config.

Log:
```
Feb 20 21:59:24 homekit homekit2mqtt[1492]: 2018-02-20 21:59:24.333 <debug> < hap set Przy oknie On false
Feb 20 21:59:24 homekit homekit2mqtt[1492]: 2018-02-20 21:59:24.341 <debug> > mqtt /AdyLight off
Feb 20 21:59:30 homekit homekit2mqtt[1492]: 2018-02-20 21:59:30.813 <debug> < hap get Przy oknie On
Feb 20 21:59:30 homekit homekit2mqtt[1492]: 2018-02-20 21:59:30.822 <debug> > hap re_get Przy oknie On true
Feb 20 21:59:32 homekit homekit2mqtt[1492]: 2018-02-20 21:59:32.802 <debug> < hap set Przy oknie On false
```

**Comment by hobbyquaker** [comment]
could you pls show me the config of the LightBulb?

**Comment by sembsa** [comment]
`
{
  "shk.01.001": {
    "id": "shk.01.001",
    "name": "Przy oknie",
    "manufacturer": "Sembsa HomeKit",
    "model": "LB0001",
    "serial": "SHK8FA001",
    "payloadIdentify": "select",
    "services": [
      {
        "name": "Przy oknie",
        "service": "Lightbulb",
        "topic": {
          "setOn": "/AdyLight",
          "statusOn": "/AdyLight",
          "setBrightness": "",
          "statusBrightness": "",
          "setHue": "",
          "statusHue": "",
          "setSaturation": "",
          "statusSaturation": "",
          "setColorTemperature": "",
          "statusColorTemperature": "",
          "statusRGB": "",
          "setRGB": ""
        },
        "payload": {
          "onTrue": "on",
          "onFalse": "off",
          "brightnessFactor": null,
          "hueFactor": null,
          "saturationFactor": null
        },
        "config": {},
        "props": {}
      }
    ],
    "payload": {},
    "config": {}
  }
}
`

**Comment by hobbyquaker** [comment]
Hmm I fear that won't work this way. homekit2mqtt subscribes the status topic and expects retained messages so it knows about a device state immedeatly after subscribing.
The messages that homekit2mqtt publishes on the set topic on the contrary are _not_ retained, so if you use the same topic for set and status there will be no retained message. I think there are two possibilities for you:
* You could change your lightbulbs interface/firmware so that it publishes it's current status retained on another topic, so you have different topics for set and status
* You could just omit the configuration of the status topic, leave it empty. But I'm not 100% sure if your accessory will then show the correct status when you restart the Home.app, you have to try out.
